import "./globals.css";
import "./custom.scss";
import Navbar from "@/components/navbar";
import { Outfit } from "next/font/google";

const outfit = Outfit({
  subsets: ["latin"],
});

export const metadata = {
  title: "36 Agents",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' data-theme='36agents' className={outfit.className}>
      <head>
        <link
          rel='icon'
          href='/assets/brand/favicon.svg'
          type='image/svg+xml'
        />
      </head>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
